### ISSUE TITLE
Crash on SetupWorkerThread  ( iOS)

### ISSUE THREAD

**Issue by kenfourdesire** [AdColony/AdColony-Unity-SDK-3#26]
Error log: 
Crashed: AdColony Worker
0  JavaScriptCore                 0x189fceae8 bmalloc::Heap::allocateLarge(std::__1::lock_guard<bmalloc::StaticMutex>&, unsigned long, unsigned long) + 24
1  JavaScriptCore                 0x189fceadc bmalloc::Heap::allocateLarge(std::__1::lock_guard<bmalloc::StaticMutex>&, unsigned long, unsigned long) + 12
2  JavaScriptCore                 0x189fcca1c bmalloc::Allocator::allocateLarge(unsigned long) + 92
3  JavaScriptCore                 0x189fcc8a8 bmalloc::Allocator::reallocate(void*, unsigned long) + 424
4  JavaScriptCore                 0x189fb9d2c WTF::StringImpl::reallocate(WTF::Ref<WTF::StringImpl>&&, unsigned int, unsigned char*&) + 76
5  JavaScriptCore                 0x1896181f0 void WTF::StringBuilder::reallocateBuffer<unsigned char>(unsigned int) + 104
6  JavaScriptCore                 0x189fb9598 WTF::StringBuilder::appendQuotedJSONString(WTF::String const&) + 172
7  JavaScriptCore                 0x189d4b0c0 JSC::Stringifier::appendStringifiedValue(WTF::StringBuilder&, JSC::JSValue, JSC::Stringifier::Holder const&, JSC::PropertyNameForFunctionCall const&) + 1624
8  JavaScriptCore                 0x189d4c7c8 JSC::Stringifier::Holder::appendNextProperty(JSC::Stringifier&, WTF::StringBuilder&) + 2716
9  JavaScriptCore                 0x189d4b594 JSC::Stringifier::appendStringifiedValue(WTF::StringBuilder&, JSC::JSValue, JSC::Stringifier::Holder const&, JSC::PropertyNameForFunctionCall const&) + 2860
10 JavaScriptCore                 0x189d4a884 JSC::Stringifier::stringify(JSC::Handle<JSC::Unknown>) + 268
11 JavaScriptCore                 0x189d4edc8 JSC::JSONProtoFuncStringify(JSC::ExecState*) + 376
12 JavaScriptCore                 0x189de2f9c llint_entry + 28940
13 JavaScriptCore                 0x189de25d0 llint_entry + 26432
14 JavaScriptCore                 0x189de25d0 llint_entry + 26432
15 JavaScriptCore                 0x189de25d0 llint_entry + 26432
16 JavaScriptCore                 0x189de256c llint_entry + 26332
17 JavaScriptCore                 0x189de256c llint_entry + 26332
18 JavaScriptCore                 0x189de25d0 llint_entry + 26432
19 JavaScriptCore                 0x189de25d0 llint_entry + 26432
20 JavaScriptCore                 0x189de25d0 llint_entry + 26432
21 JavaScriptCore                 0x189ddbcc8 vmEntryToJavaScript + 264
22 JavaScriptCore                 0x189cc5710 JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 164
23 JavaScriptCore                 0x189c9d984 JSC::Interpreter::executeProgram(JSC::SourceCode const&, JSC::ExecState*, JSC::JSObject*) + 12052
24 JavaScriptCore                 0x1899ba310 JSC::evaluate(JSC::ExecState*, JSC::SourceCode const&, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&) + 348
25 JavaScriptCore                 0x189cf9458 JSEvaluateScript + 476
26 JavaScriptCore                 0x189d0777c -[JSContext evaluateScript:withSourceURL:] + 112
27 fortunecity                    0x101c7d374 __52-[ADCJSCoreModule initWithSource:originNumber:info:]_block_invoke_2.465 (ADCJSCoreModule.m:514)
28 fortunecity                    0x101c970cc __57+[ADCWebServicesAPI postWithDict:andModuleID:completion:]_block_invoke (ADCWebServicesAPI.m:255)
29 fortunecity                    0x101cb913c __83-[ADCHTTPConnection initWithRequest:httpSession:followRedirects:completionHandler:]_block_invoke.20 (ADCHTTPConnection.m:41)
30 Foundation                     0x18623350c __NSThreadPerformPerform + 340
31 CoreFoundation                 0x1856ed42c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
32 CoreFoundation                 0x1856ecd9c __CFRunLoopDoSources0 + 540
33 CoreFoundation                 0x1856ea9a8 __CFRunLoopRun + 744
34 CoreFoundation                 0x18561ada4 CFRunLoopRunSpecific + 424
35 Foundation                     0x186135db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
36 fortunecity                    0x101cdd5bc -[AdColony setupWorkerThread] (AdColony.m:136)
37 Foundation                     0x186233318 __NSThread__start__ + 996
38 libsystem_pthread.dylib        0x18480168c _pthread_body + 240
39 libsystem_pthread.dylib        0x18480159c _pthread_body + 282
40 libsystem_pthread.dylib        0x1847fecb4 thread_start + 4

**Comment by llmagicll** [comment]
We have this issue on two of our apps with the latest version 3.1.0. Once it happened, the app cannot be opened successfully anymore. Because every time while the app is launching, it try setupWorkerThread and fail. It seems related to the data download from the server? Please help us to fix this critical issue. Thanks!

**Comment by cmanibog-ac** [comment]
@kenfourdesire I've reached out to our Engineering team for additional guidance on this crash. We'll follow up with more information after they review these details. 

@llmagicll For clarification, is this crash occurring on iOS builds of the app as well? Please share a full console log showing the app activity from when our SDK is initialized through the crash.

**Comment by cmanibog-ac** [comment]
@kenfourdesire @llmagicll Our team has seen this crash reported due to parsing of special characters (e.g. korean, japanese, etc). Is this crash seen in a specific region and could you let us know where you are testing from?

**Comment by llmagicll** [comment]
@cmanibog-ac Most of exceptions are from CJK languages. We have two apps (Unity build iOS) are having this issue: 

1. appc901bc9706bb4d5f93 zone_id: vz6901254abcda4b12a1 
2. app21c3737361bd4cad8e zone_id: v4vcdbde2c6ab2a64ea988 (This app used Admob mediation with Adcolony, we temporarily disabled the mediation now because of the crash)

**Comment by llmagicll** [comment]
@cmanibog-ac  Due to the crash issue and the great affected number of users, we currently shutdown Adcolony iOS of our two products. Because once it happens to an user, he/she has to remove the app and reinstall it. If there is any further progress, please notify and let us know. Thank you very much.

**Comment by torufuruya** [comment]
Any update on this thread?

**Comment by cmanibog-ac** [comment]
Our Engineering team has opened a ticket to track this issue and are working on a fix for a future update. At this time, we do not have a targeted release date for this update.

**Comment by torufuruya** [comment]
My crash log is slightly different (especially third block?) but is it same problem?

```sh
Thread 55 name:  AdColony Worker
Thread 55 Crashed:
0   JavaScriptCore                	0x0000000190ad6ae8 bmalloc::Heap::allocateLarge(std::__1::lock_guard<bmalloc::StaticMutex>&, unsigned long, unsigned long) + 24
1   JavaScriptCore                	0x0000000190ad4a1c bmalloc::Allocator::allocateLarge(unsigned long) + 92
2   JavaScriptCore                	0x0000000190ad48a8 bmalloc::Allocator::reallocate(void*, unsigned long) + 424
3   JavaScriptCore                	0x0000000190ac1ddc WTF::StringImpl::reallocate(WTF::Ref<WTF::StringImpl>&&, unsigned int, unsigned short*&) + 84
4   JavaScriptCore                	0x000000019012ec4c void WTF::StringBuilder::reallocateBuffer<unsigned short>(unsigned int) + 112
5   JavaScriptCore                	0x0000000190ac1598 WTF::StringBuilder::appendQuotedJSONString(WTF::String const&) + 172
6   JavaScriptCore                	0x00000001908530c0 JSC::Stringifier::appendStringifiedValue(WTF::StringBuilder&, JSC::JSValue, JSC::Stringifier::Holder const&, JSC::PropertyNameForFunctionCall const&) + 1624
7   JavaScriptCore                	0x00000001908547c8 JSC::Stringifier::Holder::appendNextProperty(JSC::Stringifier&, WTF::StringBuilder&) + 2716
8   JavaScriptCore                	0x0000000190853594 JSC::Stringifier::appendStringifiedValue(WTF::StringBuilder&, JSC::JSValue, JSC::Stringifier::Holder const&, JSC::PropertyNameForFunctionCall const&) + 2860
9   JavaScriptCore                	0x0000000190852884 JSC::Stringifier::stringify(JSC::Handle<JSC::Unknown>) + 268
10  JavaScriptCore                	0x0000000190856dc8 JSC::JSONProtoFuncStringify(JSC::ExecState*) + 376
11  JavaScriptCore                	0x00000001908eaf9c llint_entry + 28940
12  JavaScriptCore                	0x00000001908ea5d0 llint_entry + 26432
13  JavaScriptCore                	0x00000001908ea5d0 llint_entry + 26432
14  JavaScriptCore                	0x00000001908ea5d0 llint_entry + 26432
15  JavaScriptCore                	0x00000001908ea56c llint_entry + 26332
16  JavaScriptCore                	0x00000001908ea56c llint_entry + 26332
17  JavaScriptCore                	0x00000001908ea5d0 llint_entry + 26432
18  JavaScriptCore                	0x00000001908ea5d0 llint_entry + 26432
19  JavaScriptCore                	0x00000001908ea5d0 llint_entry + 26432
20  JavaScriptCore                	0x00000001908e3cc8 vmEntryToJavaScript + 264
21  JavaScriptCore                	0x00000001907cd710 JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 164
22  JavaScriptCore                	0x00000001907a5984 JSC::Interpreter::executeProgram(JSC::SourceCode const&, JSC::ExecState*, JSC::JSObject*) + 12052
23  JavaScriptCore                	0x00000001904c2310 JSC::evaluate(JSC::ExecState*, JSC::SourceCode const&, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&) + 348
24  JavaScriptCore                	0x0000000190801458 JSEvaluateScript + 476
25  JavaScriptCore                	0x000000019080f77c -[JSContext evaluateScript:withSourceURL:] + 112
26  NBGI0160                      	0x00000001012fe678 ADCGCDWebServerComputeMD5Digest + 101804
27  NBGI0160                      	0x00000001013182a8 ADCGCDWebServerComputeMD5Digest + 207324
28  NBGI0160                      	0x0000000101339f74 ADCGCDWebServerComputeMD5Digest + 345768
29  Foundation                    	0x000000018cd3b50c __NSThreadPerformPerform + 340
30  CoreFoundation                	0x000000018c1f542c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
31  CoreFoundation                	0x000000018c1f4d9c __CFRunLoopDoSources0 + 540
32  CoreFoundation                	0x000000018c1f29a8 __CFRunLoopRun + 744
33  CoreFoundation                	0x000000018c122da4 CFRunLoopRunSpecific + 424
34  Foundation                    	0x000000018cc3ddb4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
35  NBGI0160                      	0x000000010135dae8 ADCFullLog + 141244
36  Foundation                    	0x000000018cd3b318 __NSThread__start__ + 996
37  libsystem_pthread.dylib       	0x000000018b30968c _pthread_body + 240
38  libsystem_pthread.dylib       	0x000000018b30959c _pthread_body + 0
39  libsystem_pthread.dylib       	0x000000018b306cb4 thread_start + 4
```

**Comment by cmanibog-ac** [comment]
Crash has been fixed in our 3.2 SDK update.

**Comment by yutoyazaki** [comment]
This issue still occurred in SDK 3.2.1.
I've took a test of launching AdColony's sample app repeatedly. And very rarely it crashed.
A crash log is same as above.

```
Thread 7 name:  AdColony Worker
Thread 7 Crashed:
0   JavaScriptCore                	0x00000001908921c8 bmalloc::Heap::allocateLarge+ 9277896 (std::__1::lock_guard<bmalloc::StaticMutex>&, unsigned long, unsigned long) + 24
1   JavaScriptCore                	0x0000000190890594 bmalloc::Allocator::allocateLarge+ 9270676 (unsigned long) + 92
2   JavaScriptCore                	0x0000000190890420 bmalloc::Allocator::reallocate+ 9270304 (void*, unsigned long) + 428
3   JavaScriptCore                	0x000000019087e3dc WTF::StringImpl::reallocate+ 9196508 (WTF::Ref<WTF::StringImpl>&&, unsigned int, unsigned char*&) + 72
4   JavaScriptCore                	0x000000018ffbbec8 void WTF::StringBuilder::reallocateBuffer<unsigned char>+ 11976 (unsigned int) + 104
5   JavaScriptCore                	0x000000019087dc70 WTF::StringBuilder::appendQuotedJSONString+ 9194608 (WTF::String const&) + 176
6   JavaScriptCore                	0x0000000190648934 JSC::Stringifier::appendStringifiedValue+ 6879540 (WTF::StringBuilder&, JSC::JSValue, JSC::JSObject*, JSC::PropertyNameForFunctionCall const&) + 3120
7   JavaScriptCore                	0x0000000190649a94 JSC::Stringifier::Holder::appendNextProperty+ 6883988 (JSC::Stringifier&, WTF::StringBuilder&) + 2732
8   JavaScriptCore                	0x0000000190648ca4 JSC::Stringifier::appendStringifiedValue+ 6880420 (WTF::StringBuilder&, JSC::JSValue, JSC::JSObject*, JSC::PropertyNameForFunctionCall const&) + 4000
9   JavaScriptCore                	0x0000000190647ae8 JSC::Stringifier::stringify+ 6875880 (JSC::Handle<JSC::Unknown>) + 372
10  JavaScriptCore                	0x000000019064c160 JSC::JSONProtoFuncStringify+ 6893920 (JSC::ExecState*) + 408
11  JavaScriptCore                	0x00000001906e1064 llint_entry + 27476
12  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
13  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
14  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
15  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
16  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
17  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
18  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
19  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
20  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
21  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
22  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
23  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
24  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
25  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
26  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
27  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
28  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
29  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
30  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
31  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
32  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
33  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
34  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
35  JavaScriptCore                	0x00000001906e064c llint_entry + 24892
36  JavaScriptCore                	0x00000001906da348 vmEntryToJavaScript + 264
37  JavaScriptCore                	0x00000001905aca8c JSC::JITCode::execute+ 6240908 (JSC::VM*, JSC::ProtoCallFrame*) + 168
38  JavaScriptCore                	0x000000018ffe66e0 JSC::Interpreter::execute+ 186080 (JSC::ProgramExecutable*, JSC::ExecState*, JSC::JSObject*) + 13724
39  JavaScriptCore                	0x00000001902c9f74 JSC::evaluate+ 3215220 (JSC::ExecState*, JSC::SourceCode const&, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&) + 440
40  JavaScriptCore                	0x00000001905dcbb4 JSEvaluateScript + 448
41  JavaScriptCore                	0x00000001905eaa20 -[JSContext evaluateScript:withSourceURL:] + 112
42  AdColonyV4VC                  	0x0000000100036920 -[ADCJSCoreModule beginMessagePassing:] + 174368 (ADCJSCoreModule.m:627)
43  AdColonyV4VC                  	0x000000010002b3e8 -[ADCController beginMessagePassingWithControllerSource:] + 127976 (ADCController.m:386)
44  AdColonyV4VC                  	0x0000000100029ee0 -[ADCController loadWithCompletion:] + 122592 (ADCController.m:208)
45  AdColonyV4VC                  	0x000000010005fe68 __32-[ADCNativeLayer loadController]_block_invoke + 343656 (ADCNativeLayer.m:141)
46  Foundation                    	0x000000018cbc9048 __NSThreadPerformPerform + 340
47  CoreFoundation                	0x000000018c062b5c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
48  CoreFoundation                	0x000000018c0624a4 __CFRunLoopDoSources0 + 524
49  CoreFoundation                	0x000000018c0600a4 __CFRunLoopRun + 804
50  CoreFoundation                	0x000000018bf8e2b8 CFRunLoopRunSpecific + 444
51  Foundation                    	0x000000018cacb26c -[NSRunLoop+ 49772 (NSRunLoop) runMode:beforeDate:] + 304
52  AdColonyV4VC                  	0x000000010009eee0 -[AdColony setupWorkerThread] + 601824 (AdColony.m:156)
53  Foundation                    	0x000000018cbc8e68 __NSThread__start__ + 1024
54  libsystem_pthread.dylib       	0x000000018b149850 _pthread_body + 240
55  libsystem_pthread.dylib       	0x000000018b149760 _pthread_body + 0
56  libsystem_pthread.dylib       	0x000000018b146d94 thread_start + 4

```

**Comment by AlbertRenshaw** [comment]
How is this not fixed yet? Many of our paid users are reporting inability to open their app, this is the issue we found when inspecting crash logs.

**Comment by shawnkc** [comment]
Hello, sorry that we didn't update this issue after it was previously closed. 

We also were able to reproduce the issue, but have addressed it in v3.3.0. Do you have crash logs from any version using v3.3.0? Our QA team is retesting the sample app right now.

**Comment by AlbertRenshaw** [comment]
We are using Appodeal's newest SDK, I assume they are using your 3.3.0 SDK but I can't know as it's all bundled into their files. 
[Auto Video Crash.zip](https://github.com/AdColony/AdColony-Unity-SDK-3/files/1773287/Auto.Video.Crash.zip)

**Comment by shawnkc** [comment]
It looks like Appodeal is using 3.2.1. https://www.appodeal.com/sdk/documentation?framework=21&full=1&platform=4#p_5

Also, I didn't see any AdColony code in the crashing thread within the stack trace you provided.

Our QA department was unable to reproduce the problem yesterday with the Unity 3.3.0 sample app. Please let us know if you have any other issues.
